// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/3/2025, 3:52:23 p. m.
const configMerger = require("F:/Henry/github/base-nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["F:/Henry/github/base-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Henry/github/base-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Henry/github/base-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Henry/github/base-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Henry/github/base-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Henry/github/base-nuxt/plugins/**/*.{js,ts,mjs}","F:/Henry/github/base-nuxt/composables/**/*.{js,ts,mjs}","F:/Henry/github/base-nuxt/utils/**/*.{js,ts,mjs}","F:/Henry/github/base-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/Henry/github/base-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/Henry/github/base-nuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
